### ISSUE TITLE
flycast fails to build on linux after #773 (fix included)

### ISSUE THREAD

**Issue by asavah** [libretro/flycast#775]
After #773 flycast fails to build on linux.

```
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/vulkan_renderer.o: in function `VulkanRenderer::Render()':
vulkan_renderer.cpp:(.text._ZN14VulkanRenderer6RenderEv[_ZN14VulkanRenderer6RenderEv]+0x9c): undefined reference to `VulkanOSD::DrawOSD(vk::CommandBuffer, vk::Extent2D)'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/vulkan_renderer.o: in function `VulkanRenderer::Term()':
vulkan_renderer.cpp:(.text._ZN14VulkanRenderer4TermEv[_ZN14VulkanRenderer4TermEv]+0x44): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/vulkan_renderer.o: in function `VulkanRenderer::Init()':
vulkan_renderer.cpp:(.text._ZN14VulkanRenderer4InitEv[_ZN14VulkanRenderer4InitEv]+0xf1): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/vulkan_renderer.o: in function `VulkanRenderer::Process(TA_context*)':
vulkan_renderer.cpp:(.text._ZN14VulkanRenderer7ProcessEP10TA_context[_ZN14VulkanRenderer7ProcessEP10TA_context]+0x65b): undefined reference to `VulkanOSD::PrepareOSD(CommandPool*)'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/vulkan_renderer.o: in function `VulkanRenderer::~VulkanRenderer()':
vulkan_renderer.cpp:(.text._ZN14VulkanRendererD2Ev[_ZN14VulkanRendererD5Ev]+0x2f): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/oit/oit_renderer.o: in function `OITVulkanRenderer::Render()':
oit_renderer.cpp:(.text._ZN17OITVulkanRenderer6RenderEv[_ZN17OITVulkanRenderer6RenderEv]+0x9c): undefined reference to `VulkanOSD::DrawOSD(vk::CommandBuffer, vk::Extent2D)'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/oit/oit_renderer.o: in function `OITVulkanRenderer::Term()':
oit_renderer.cpp:(.text._ZN17OITVulkanRenderer4TermEv[_ZN17OITVulkanRenderer4TermEv]+0x44): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/oit/oit_renderer.o: in function `OITVulkanRenderer::Init()':
oit_renderer.cpp:(.text._ZN17OITVulkanRenderer4InitEv[_ZN17OITVulkanRenderer4InitEv]+0x207): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/oit/oit_renderer.o: in function `OITVulkanRenderer::~OITVulkanRenderer()':
oit_renderer.cpp:(.text._ZN17OITVulkanRendererD2Ev[_ZN17OITVulkanRendererD5Ev]+0x2f): undefined reference to `VulkanOSD::~VulkanOSD()'
/home/asavah/kross/host/asusb450eg/lib/gcc/x86_64-asusb450eg-linux-gnu/9.2.1/../../../../x86_64-asusb450eg-linux-gnu/bin/ld: ./core/rend/vulkan/oit/oit_renderer.o: in function `OITVulkanRenderer::Process(TA_context*)':
oit_renderer.cpp:(.text._ZN17OITVulkanRenderer7ProcessEP10TA_context[_ZN17OITVulkanRenderer7ProcessEP10TA_context]+0x66b): undefined reference to `VulkanOSD::PrepareOSD(CommandPool*)'
collect2: error: ld returned 1 exit status
```

The fix is trivial vmu.cpp was not included in Makefile.common

patch:
```
diff --git a/Makefile.common b/Makefile.common
index bec6fff0..8c33920f 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -303,6 +303,7 @@ ifeq ($(HAVE_VULKAN), 1)
                                        $(CORE_DIR)/core/rend/vulkan/quad.cpp \
                                        $(CORE_DIR)/core/rend/vulkan/shaders.cpp \
                                        $(CORE_DIR)/core/rend/vulkan/texture.cpp \
+                                       $(CORE_DIR)/core/rend/vulkan/vmu.cpp \
                                        $(CORE_DIR)/core/rend/vulkan/vulkan_renderer.cpp \
                                        $(CORE_DIR)/core/rend/vulkan/oit/oit_drawer.cpp \
                                        $(CORE_DIR)/core/rend/vulkan/oit/oit_pipeline.cpp \

```
If you prefer the fix PRed just let me know.

**Comment by flyinghead** [comment]
Just pushed a fix: https://github.com/libretro/flycast/commit/37c2286c655818f2eb1288af83ad76b8ea74aa36
Thanks

**Comment by asavah** [comment]
Thanks
